[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd app && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn config.wsgi --bind 0.0.0.0:$PORT"

[volumes]
news-data-storage = { mount = "/app/data" }