# Generated by Django 4.2.7 on 2025-10-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-published_at", "-created_at"]},
        ),
        migrations.AddField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(
                blank=True, help_text="Article publication date from source", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-published_at"], name="news_articl_publish_62720b_idx"
            ),
        ),
    ]
